// Данные курса — все плейлисты и видео
const COURSE_DATA = {
  days: [
    {
      id: 1,
      title: "День 1",
      subtitle: "Введение в систему управления",
      playlist: "PLuHIwD8UzKjwehooi2D3Ax3wbVndFOI7D",
      videos: [
        { id: 1, title: "Приветствие, знакомство, регламент", url: "https://youtu.be/ukzQhD77DAM" },
        { id: 2, title: "Александр Высоцкий — биография", url: "" },
        { id: 3, title: "О бизнес-бустере — программа 6 дней", url: "" },
        { id: 4, title: "Три роли владельца-директора", url: "" },
        { id: 5, title: "Функции владельца бизнеса", url: "" },
        { id: 6, title: "Пять стадий развития бизнеса", url: "" },
        { id: 7, title: "Проблемы ручного управления и почти системы", url: "" },
        { id: 8, title: "Примеры Nintendo Kodak Apple адвайзер-борд", url: "" },
        { id: 9, title: "Партнерство ошибки совладельцев", url: "" },
        { id: 10, title: "Оргструктура задание QnA", url: "https://youtu.be/ukzQhD77DAM" },
      ]
    },
    {
      id: 2,
      title: "День 2",
      subtitle: "Оргструктура и функции",
      playlist: "PLuHIwD8UzKjxUQLTuMnrViXyIM5hXRBtG",
      videos: [
        { id: 1, title: "Перелинное планирование — основные принципы", url: "https://youtu.be/uukxwgOPH_Q" },
        { id: 2, title: "После найма", url: "https://youtu.be/x6Okvb45nZw" },
        { id: 3, title: "Практическое задание — знакомство", url: "https://youtu.be/zH6dlzet0xc" },
        { id: 4, title: "Уровни планирования", url: "https://youtu.be/NOHAexbJpLU" },
        { id: 5, title: "Быстрый найм и введение в должность", url: "https://youtu.be/D7KC94e8M7k" },
        { id: 6, title: "Выполнение задания 2.1–2.2", url: "https://youtu.be/fTBChgSUcZo" },
        { id: 7, title: "Орг. структура из 7 департаментов", url: "https://youtu.be/Cv8Jg6bOsqM" },
        { id: 8, title: "Оргструктура из 21 отдела", url: "https://youtu.be/jhL3j2XK2G8" },
        { id: 9, title: "Оргструктура", url: "https://youtu.be/GsdZmvYFiBo" },
        { id: 10, title: "Ответы на вопросы из чата", url: "https://youtu.be/zvxRN5AZHuY" },
        { id: 11, title: "Упомянутые функции", url: "https://youtu.be/11n57-yrhnk" },
        { id: 12, title: "Эффективное взаимодействие", url: "https://youtu.be/8J45wsNyJ8k" },
      ]
    },
    {
      id: 3,
      title: "День 3",
      subtitle: "Метрики и координация",
      playlist: "PLuHIwD8UzKjwXOJjU327qL1j5tRD_c1Ys",
      videos: [
        { id: 1, title: "Что такое метрика — Пример с типографией", url: "https://youtu.be/rS7vAZTUR5g" },
        { id: 2, title: "Сложные метрики — ПР и имидж компании", url: "https://youtu.be/xGQ1TmsZEhY" },
        { id: 3, title: "Польза метрик — История с Леной", url: "https://youtu.be/T76XVu_R07E" },
        { id: 4, title: "Метрики и выход из операционки", url: "https://youtu.be/mReosWzlCQA" },
        { id: 5, title: "Координация — Определение и примеры", url: "https://youtu.be/sIFXAlP0Cr0" },
        { id: 6, title: "Управленческая и функциональная координация", url: "https://youtu.be/-SXcwIIU4K0" },
        { id: 7, title: "Примеры координации в бизнесе", url: "https://youtu.be/gcsIf17fwAw" },
        { id: 8, title: "Три принципа успешной координации", url: "https://youtu.be/EJHibhNIWpQ" },
        { id: 9, title: "Задание 3.1 — График валового дохода", url: "https://youtu.be/GfVHWp4BFQ8" },
        { id: 10, title: "Задание 3.2 — Список координаций", url: "https://youtu.be/5DLitdTg7TY" },
        { id: 11, title: "Вопросы и ответы — Систематизация и метрики", url: "https://youtu.be/enR2bdT68iA" },
        { id: 12, title: "Вопросы и ответы — Мотивация и зарплата", url: "https://youtu.be/Gdj5jx4laxg" },
        { id: 13, title: "Вопросы и ответы — Метрики для разных должностей", url: "https://youtu.be/RZrKiOdT_O0" },
        { id: 14, title: "Вопросы и ответы — Сезонность и координации", url: "https://youtu.be/eGuMgCzm8hQ" },
        { id: 15, title: "Вопросы и ответы — Диагностика и завершение", url: "https://youtu.be/lpfSPQtzel0" },
      ]
    },
    {
      id: 4,
      title: "День 4",
      subtitle: "Маркетинг и продажи",
      playlist: "PLuHIwD8UzKjy226xg58xXKHmmTS0rV-BQ",
      videos: [
        { id: 1, title: "Введение и подготовка к практическому занятию", url: "https://youtu.be/PXgu_Eonc4I" },
        { id: 2, title: "Разбор заданий по предыдущему дню", url: "https://youtu.be/R53UrQHWRBc" },
        { id: 3, title: "Кейс — Анализ успешных действий на примере Александра", url: "https://youtu.be/Jt4BuUOs-40" },
        { id: 4, title: "Кейс — Сезонность и ошибки в ценообразовании", url: "https://youtu.be/2lXoeiaxZgA" },
        { id: 5, title: "Кейс — Неэффективные продажи на примере Олега", url: "https://youtu.be/EIxMlLzJ7Mk" },
        { id: 6, title: "Реальные кейсы и осознания участников", url: "https://youtu.be/etKeybVwFgc" },
        { id: 7, title: "Начало вебинара Валентина по маркетингу", url: "https://youtu.be/Ry_1pNc4874" },
        { id: 8, title: "Как систематизировать маркетинг в компании", url: "https://youtu.be/gRZDJ54Js6E" },
        { id: 9, title: "Основы маркетинга — подход к управлению", url: "https://youtu.be/ZA5KNmBM8mQ" },
        { id: 10, title: "Главный маркетинговый вопрос и ошибки", url: "https://youtu.be/1EVywkKt8Qk" },
        { id: 11, title: "Примеры провалов из-за ошибок в маркетинге", url: "https://youtu.be/B65osuITLmQ" },
        { id: 12, title: "Заземление — как не потерять контакт с рынком", url: "https://youtu.be/Tw1GSgfFnW4" },
        { id: 13, title: "Анализ конкурентов — самый быстрый способ", url: "https://youtu.be/fPCRuEMiI3U" },
        { id: 14, title: "Почему важно знать целевую аудиторию", url: "https://youtu.be/MOvUL625Bas" },
        { id: 15, title: "Боли целевой аудитории — как собрать информацию", url: "https://youtu.be/hDDlH-WU3D8" },
      ]
    },
    {
      id: 5,
      title: "День 5",
      subtitle: "Система управления финансами",
      playlist: "PLuHIwD8UzKjwMQsUN4WFetpgHaypT-4uu",
      videos: [
        { id: 1, title: "Открытие дня — Знакомство с Алексеем", url: "https://youtu.be/RLYqj_LYhCc" },
        { id: 2, title: "Разбор кейсов — маркетинг и продажи", url: "https://youtu.be/CDKLDbnQ0Bs" },
        { id: 3, title: "Осознания участников — Итоги блока маркетинга", url: "https://youtu.be/1QrV833SfB8" },
        { id: 4, title: "Вступление Александра — Удача и цели владельца", url: "https://youtu.be/c6pD9UJkWWM" },
        { id: 5, title: "Система управления финансами — Вводная", url: "https://youtu.be/2jSp_294FzE" },
        { id: 6, title: "Почему владелец застревает в операционке финансов", url: "https://youtu.be/Rkva7zjYQA4" },
        { id: 7, title: "Разделение счетов — основа системы", url: "https://youtu.be/7zfHU7sdIYQ" },
        { id: 8, title: "Финансовая модель распределения средств", url: "https://youtu.be/CPi8D_VEVUg" },
        { id: 9, title: "Еженедельное планирование — Рекомендательный совет", url: "https://youtu.be/RU-aNilvz7Q" },
        { id: 10, title: "Полная прозрачность финансов для руководителей", url: "https://youtu.be/hgEwnd3a-Yo" },
        { id: 11, title: "Обязанности владельца — Финансовый инструмент", url: "https://youtu.be/pzmAu5rcnyA" },
        { id: 12, title: "Практическое задание — Екатерина, бонусы", url: "https://youtu.be/brriLW3hRy4" },
        { id: 13, title: "Ответы на вопросы", url: "https://youtu.be/f106xA-OgRA" },
      ]
    },
    {
      id: 6,
      title: "День 6",
      subtitle: "Внедрение и итоги",
      playlist: "PLuHIwD8UzKjxiSmX0VB_75TNKdKwtA293",
      videos: [
        { id: 1, title: "Открытие дня — recap", url: "https://youtu.be/Yy5AzGeuGKg" },
        { id: 2, title: "Разбор заданий День 5 — финансы", url: "https://youtu.be/s7L158K4X2o" },
        { id: 3, title: "Как внедрять изменения", url: "https://youtu.be/LMHCN8sBJFY" },
        { id: 4, title: "Идеология — оргсхема, метрики", url: "https://youtu.be/V3jNNrhqMLM" },
        { id: 5, title: "Делегирование, найм, планирование", url: "https://youtu.be/bpM-K3gRx1E" },
        { id: 6, title: "Координация и управление финансами", url: "https://youtu.be/1AsxRYn90kI" },
        { id: 7, title: "Управление продажами и маркетинг", url: "https://youtu.be/aqLf1_wgMcA" },
        { id: 8, title: "Ошибки внедрения", url: "https://youtu.be/7VdnEFWrlBU" },
        { id: 9, title: "Платформа бизнес-бустер", url: "https://youtu.be/X20s_iMFdUs" },
        { id: 10, title: "Структура программы — 5 уровней", url: "https://youtu.be/Ddn4yUzW-EY" },
        { id: 11, title: "Варианты участия и предложение", url: "https://youtu.be/8Hrh9IW7xxY" },
        { id: 12, title: "Вопросы и ответы — завершение", url: "https://youtu.be/u1tVXl7eaM0" },
      ]
    },
  ],
  bonuses: [
    {
      id: "bonus1",
      title: "Бонус 1",
      subtitle: "Копирайтинг и маркетинг-кит",
      url: "https://youtu.be/",
    },
    {
      id: "bonus2",
      title: "Бонус 2",
      subtitle: "Стратегическое планирование",
      url: "https://youtu.be/",
    },
    {
      id: "bonus3",
      title: "Бонус 3",
      subtitle: "Личный бренд и сообщества",
      url: "https://youtu.be/",
    },
  ],
  instruments: {
    playlist2026: "PLuHIwD8UzKjyDvo1I992H57blcW6U2vR1",
    playlist2025: "",
  }
};
